### ISSUE TITLE
Add support for windows_amd64

### ISSUE THREAD

**Issue by ProtoTRR** [mindee/terraform-provider-uptimerobot#3]
Provider registry.terraform.io/mindee/uptimerobot v1.0.0 does not have a package available for your current platform, windows_amd64.

**Comment by paretl** [comment]
Thanks for reporting this! I think that's a good feature that should be added. I can make it but if anyone wants to make a PR about that, feel free

**Comment by paretl** [comment]
Hey, I added the support for windows on [this commit](https://github.com/mindee/terraform-provider-uptimerobot/commit/7840a8fc897380148f46926c81221722ef497dfe). This change is available from the version [1.1.4 ](https://registry.terraform.io/providers/mindee/uptimerobot/1.1.4)
I did not have the opportunity to test it correctly, feel free to re-open this issue if you see something wrong.
